### ISSUE TITLE
shops don't work with the Latest QB update

### ISSUE THREAD

**Issue by Ben1Tou** [Project-Sloth/ps-inventory#102]
When you try to open a store, you get the following error.
[     script:qb-shops] SCRIPT ERROR: @qb-shops/server/main.lua:166: No such export CreateShop in resource qb-inventory

change the trigger in qb-shops to ps-inventory and still no diffrence
[     script:qb-shops] SCRIPT ERROR: @qb-shops/server/main.lua:166: No such export CreateShop in resource ps-inventory

![Schermafbeelding 2024-06-25 004441](https://github.com/Project-Sloth/ps-inventory/assets/173740033/d6c0eecf-ed98-4d9b-97aa-1f8a35b9a486)

**Comment by LoudBlowinChungus** [comment]
lots of things have stopped working with the new qb-core upadates. please update ps-inventory so it works with the new qb-core. project sloth makes everything look and run so much better than plain qb. Thank you

**Comment by MonkeyWhisper** [comment]
Update it yourself.

**Comment by madmechanic187** [comment]
same issue upadted qb-core but it cant find export in main

**Comment by xFutte** [comment]
@Ben1Tou Feel free to update it yourself and make a PR.

**Comment by madmechanic187** [comment]
what do you mean if i download the ps inventory again and install it it sound work?
