### ISSUE TITLE
Weapon Animation Breaks

### ISSUE THREAD

**Issue by IN1GHTM4R3** [Project-Sloth/ps-inventory#12]
Weapon doesn't get pulled from your back, just appears in your hand with this inventory. I have thoroughly tested it to see why it happens but all the "weapons:client:DrawWeapon" are the same from the old inventory to this new one.

**Comment by KotianVK** [comment]
put this TriggerEvent('weapons:client:DrawWeapon', weaponName) in client from line 558 to 587
![Screenshot (1621)](https://github.com/Project-Sloth/ps-inventory/assets/120315171/1fca8ee4-8a65-4c71-ae21-310bcd4c6635)
