### ISSUE TITLE
Player Items won't save when logout 

### ISSUE THREAD

**Issue by MasterxLuke** [Project-Sloth/ps-inventory#15]
The Items in the Inventory wont save but the Items in the Stashes are saving

Does anyone have a idea why?

**Comment by jattgurry** [comment]
Didn't face this issue

**Comment by zlexif** [comment]
How did u fix this?

**Comment by Hexney272** [comment]
Same problem here. How can i fix it?

**Comment by dejadabber** [comment]
> read the read me will help

where in the read me does it help cause i cannot find squat
