### ISSUE TITLE
Color changes

### ISSUE THREAD

**Issue by zerocluu** [Project-Sloth/ps-inventory#24]
Please can you add a color configuration like lj-inventory & add inventory usage tips to the settings

**Comment by rxnm** [comment]
_Please use the GitHub issues system to report issues or make suggestions, when making suggestions, please keep [Suggestion] in the title to make it clear that it is a suggestion._

**Comment by MonkeyWhisper** [comment]
> Please can you add a color configuration like lj-inventory & add inventory usage tips to the settings

Open source, you can do it yourself
