### ISSUE TITLE
SCRIPT ERROR: @qb-core/server/player.lua:183: No such export LoadInventory in resource ps-inventory

### ISSUE THREAD

**Issue by AntMars008** [Project-Sloth/ps-inventory#56]
![image](https://github.com/Project-Sloth/ps-inventory/assets/156021835/c50aac95-1b2c-42f4-8ccb-52b7eabde2f8)
I get the above error and a black screen stuck on the 'loading' circle when I log in with a newly created character after setting up a fresh server. The only thing I've done is replace qb-inventory with ps-inventory. I followed all the instructions and all the scripts are the newest downloaded today. Even the FiveM is the newest.

This is line 739 in scheduler.lua (FiveM source):
**return table_unpack(Citizen.Await(p))**
Not sure how this relates?

This is line 183 in player.lua:
**PlayerData.items = GetResourceState('ps-inventory') ~= 'missing' and exports['ps-inventory']:LoadInventory(PlayerData.source, PlayerData.citizenid) or {}**

This is the export in ps-inventory (line 58):
**exports("LoadInventory", LoadInventory)**

I have no idea why it's not working. Any advice?

**Comment by TimansD** [comment]
Was there a solution to this? i have the same issue..
