### ISSUE TITLE
Out of proportion

### ISSUE THREAD

**Issue by ByronNF** [Project-Sloth/ps-inventory#65]
I like ps-inventory but it's all out of proportion on a 4k monitor, The text is too large the boxes are too small and there is overlap on the Give, Use boxes. is there a way to resize the text and boxes? Thanks.

![Screenshot 2024-02-12 174754a](https://github.com/Project-Sloth/ps-inventory/assets/101049797/eb751706-5a56-440d-9dfd-8e39a87afaca)

**Comment by MonkeyWhisper** [comment]
Sure, you can do it yourself, open source code.
