### ISSUE TITLE
Decay not being saved

### ISSUE THREAD

**Issue by vladyxd** [Project-Sloth/ps-inventory#69]
Inventory json from DB:

[{"created":1709666016,"amount":1,"slot":1,"info":{"quality":100},"name":"blue_phone","type":"item"},{"created":1709667236,"amount":1,"slot":2,"info":{"quality":100},"name":"medkit","type":"item"},{"created":1709729667,"amount":2,"slot":3,"info":{"quality":100},"name":"tosti","type":"item"},{"created":1709733325,"amount":1,"slot":6,"info":{"quality":91},"name":"sandwich","type":"item"}]

sandwich has decay, it is not saved, which means, after re-entering the game, it resets, right? :)
Or at least to keep it saved.. but it seems like it's not.

Which is confirmed, video:

https://youtu.be/0tzbbZXutrA

**Comment by MonkeyWhisper** [comment]
Decay does work
