### ISSUE TITLE
Crafting Not starting on server start

### ISSUE THREAD

**Issue by parham-ebrahim** [Project-Sloth/ps-inventory#7]
on start of the server, the crafting benches don't work.
after restarting the script it starts working.

https://streamable.com/yltf8n

there are no errors on start of the server
there are no errors on restarting the script

(yes im aware the name of the inventory is changed to qb-inventory instead of ps-inventory. i did the reverse instead of changing all qb-inventory to ps-inventory, i changed all ps-inventory to qb-inventory...however i tried it both ways and still having the same issue)

**Comment by Sebaavv** [comment]
same problem
