### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by MrKap32** [Project-Sloth/ps-inventory#8]
![Screenshot 2023-06-26 170301](https://github.com/Project-Sloth/ps-inventory/assets/98072582/56a14df0-5167-45ab-b919-5c5fe098f04d)
Fresh Install of the inventory. 
Resolution 344x1440

The inventory doesnt seem to like this resolution

**Comment by TheeeMonk** [comment]
I have the same problem, what did you do?

**Comment by xFutte** [comment]
> I have the same problem, what did you do?

At the moment this screen size is not supported out-of-the-box. A fix can be made by adding a @media breakpoint in the CSS for this screen resolution. Feel free to make a pull request if you choose to implement this.
