### ISSUE TITLE
2k/4k Support request

### ISSUE THREAD

**Issue by NickBroughton** [Project-Sloth/ps-inventory#82]
Could you guys add 2k / 4k fixes for the ui? it only looks normal in 1080p, in 4k/2k the ui does not adjust and it looks wonky.

**Comment by MonkeyWhisper** [comment]
You do it.

**Comment by NickBroughton** [comment]
> You do it.

I would If I knew how to code dumb fuk.

**Comment by MonkeyWhisper** [comment]
> > You do it.
> 
> wouldn't have asked If I knew how to dumb fuk.

Then learn how to do it you dumb fuck. Trying to make us work for you? Fuck off, go learn how to code you twat.
