### ISSUE TITLE
Inventory stops opening after a while and completely breaks. logs are below

### ISSUE THREAD

**Issue by Max-Storm-03** [Project-Sloth/ps-inventory#94]
[ script:ps-inventory] SCRIPT ERROR: @ps-inventory/server/main.lua:2547: attempt to sub a 'number' with a 'string'
[ script:ps-inventory] > TriggerCallback (@qb-core/server/functions.lua:456)
[ script:ps-inventory] > handler (@qb-core/server/events.lua:105)

**Comment by Max-Storm-03** [comment]
If not using decay system you can remove line @ps-inventory/server/main . lua : 2547

**Comment by MonkeyWhisper** [comment]
How about you stop spamming our issues and you fix it yourself?
